name = "chinese-grammar-checker"
main = "worker/index.ts"
compatibility_date = "2023-12-01"

# KV命名空间配置
[[kv_namespaces]]
binding = "chinese-grammar-checker-LOGS" # 在Worker中使用的变量名
id = "8c514cc9685f488c81b2447250edcd76" # 替换为你的KV命名空间ID

# 环境变量配置
[vars]
API_LOGS_TOKEN = "my-secure-api-logs-token-2025" # 在生产环境中应使用更复杂的令牌

# 可观测性配置
[observability]
enabled = true

# D1数据库配置
[[d1_databases]]
binding = "DB"
database_name = "grammar-checker-logs"
database_id = "14bba2f0-7764-4982-b1b5-81743472db41"
migrations_dir = "migrations"

